#############################################################
#
# Setting up packages according to its hosts groups
#

- name: Setup ntpd
  yum: name=ntp state=present
  tags:
  - packages
  notify:
  - ntpd start

- name: Setup CLC packages
  yum: name="{{ item }}" state=present
  with_items:
  - eucalyptus-cloud
  - eucalyptus-imaging-worker-image
  - eucalyptus-load-balancer-image
  when:
  - inventory_hostname in groups.clc
  tags:
  - clc
  - packages

- name: Setup UFS package
  yum: name="{{ item }}" state=present
  with_items:
  - eucalyptus-cloud
  - eucalyptus-osg
  when:
  - inventory_hostname in groups.ufs
  tags:
  - ufs
  - packages

- name: Setup SC package
  yum: name="{{ item }}" state=present
  with_items:
  - eucalyptus-sc
  when:
  - inventory_hostname in groups.sc
  tags:
  - sc
  - packages

- name: Setup Walrus package
  yum: name="{{ item }}" state=present
  with_items:
  - eucalyptus-walrus
  when:
  - inventory_hostname in groups.walrus
  tags:
  - walrus
  - packages

- name: Setup NC packages
  yum: name="{{ item }}" state=present
  with_items:
  - eucalyptus-nc
  - tcpdump
  - nmap
  when:
  - inventory_hostname in groups.nc
  tags:
  - nc
  - packages

- name: setup eucaneted for EDGE
  yum: name="{{ item }}" state=latest
  with_items:
  - eucanetd
  when:
  - inventory_hostname in groups.nc
  - networking_mode == "EDGE"
  tags:
  - packages
  - nc

- name: Setup CC packages
  yum: name="{{ item }}" state=present
  with_items:
  - eucalyptus-cc
  - tcpdump
  - nmap
  when:
  - inventory_hostname in groups.cc
  tags:
  - cc
  - packages
